import Link from "next/link";
import Image from "next/image";
import {
  AiOutlineSearch,
  AiFillBulb,
  AiFillRedditCircle,
} from "react-icons/ai";
import { Inter } from "next/font/google";
import Logo from "@/public/next.svg";
import "@/styles/reset.css";
import "@/styles/globals.css";
import "@/styles/header.scss";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="header-wrapper">
      <div>
        <Link href="/">
          <Image src={Logo} width={71} height={24} alt="main logo" />
        </Link>
      </div>
      <div className="btn-wrapper">
        <div>
          <AiFillBulb style={{ width: 24, height: 24 }} />
        </div>
        <div>
          <Link href="/search">
            <AiOutlineSearch style={{ width: 18, height: 18 }} />
          </Link>
        </div>
        <div className="write-btn">
          <Link href="/write">새 글 작성</Link>
        </div>
        <div>
          <AiFillRedditCircle style={{ width: 40, height: 40 }} />
        </div>
      </div>
    </header>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
